#!/usr/bin/bash

go run github.com/stephenafamo/bob/gen/bobgen-sqlite@latest -c ./bobgen.yaml

cd internal/rpc/pb || exit
protoc --go_out=. --go_opt=paths=source_relative \
  --go-grpc_out=. --go-grpc_opt=paths=source_relative \
  bot.proto
